# Generated by Django 5.0.3 on 2024-04-30 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_yorum_yorum_sahibi'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='name',
            field=models.CharField(default='yusuf', max_length=100),
        ),
    ]
