# Generated by Django 5.0.3 on 2024-05-04 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_remove_blog_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blog_text',
            field=models.TextField(blank=True, default='blog_text', null=True, verbose_name='blog_text'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='blog_title',
            field=models.CharField(default='blog_title', max_length=50),
        ),
    ]
