# Generated by Django 5.0.3 on 2024-05-04 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_blog_blog_sahibi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blog_text',
            field=models.TextField(blank=True, null=True, verbose_name='blog_text'),
        ),
    ]
