# Generated by Django 5.0.3 on 2024-05-04 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_alter_blog_blog_sahibi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='blog_sahibi',
        ),
    ]
